(function($){var siteLogo=$("header .logo a");var siteTitle=siteLogo.text();$("header .logo a").hover(function(){$(this).text("home");},function(){$(this).text(siteTitle);});var address="manos@malihu.gr";$(".address").html("<a href='mailto:"+address+"'>"+address+"</a>");$.fn.TextField=function(){return this.each(function(){var $this=$(this);var $defaultValue=$this.val();$this.focus(function(){if($this.val()==$defaultValue){$this.val("");}});$this.blur(function(){if($this.val()==""){$this.val($defaultValue);}});});}
$.fn.PageScroll=function(speed,easing){return this.each(function(){var $this=$(this);$this.click(function(e){e.preventDefault();var scrollTo=$this.attr("href").split("#");var scrollElem="html";if($.browser.webkit){scrollElem="body";}
$(scrollElem).stop().animate({scrollTop:$("#"+scrollTo[1]).offset().top},speed,easing);});});}
$.fn.CodeNoWrap=function(className){return this.each(function(){var $this=$(this);var h=$this.height();if(h>=40){var language=$this.attr("data-language");var markup="<div class='code-extras'><a class='text-wrap-toggle' title='Toggle code wrapping'>No wrap</a></div>";$this.before(markup);var codeExtras=$this.prev(".code-extras");var wrapToggle=codeExtras.children(".text-wrap-toggle");var wrapToggleTxt=wrapToggle.text();var abbrLangTitle;if(language=="javascript"){abbrLangTitle="JavaScript scripting language";}else if(language=="php"){abbrLangTitle="PHP: Hypertext Preprocessor";}else if(language=="html"){abbrLangTitle="HyperText Markup Language";}else if(language=="css"){abbrLangTitle="Cascading Style Sheets";}
codeExtras.append("<abbr title='"+abbrLangTitle+"' class='abbr-language al-"+language+"'>"+language+"</abbr>");wrapToggle.click(function(e){e.preventDefault();$this.toggleClass(className);if($(this).text()==wrapToggleTxt){$(this).text("Wrap");}else{$(this).text(wrapToggleTxt);}});}});}
$.fn.TrimIt=function(){return this.each(function(){var $this=$(this);var trimmed=$.trim($this.text());$this.text(trimmed);});}
$.fn.HiddenBlock=function(speed,easing){return this.each(function(){var $this=$(this);var title=$this.children("h3").children("a");title.append("<span class='toggle-sign'>&#x25BE;</span>");var sign=title.children(".toggle-sign");var elem=$this.children(".hidden-block-content");title.click(function(e){e.preventDefault();elem.stop().slideToggle(speed,easing,function(){if(elem.is(":hidden")){sign.html("&#x25BE;");}else{sign.html("&#x25B4;");}});});});}
$("#bsbm_form").prepend("<span class='lock icon'></span>");$("#bsbm_form label").css("padding-left",20);$("#bsbm_form .notice").append("<span class='asterisc'>*</span>");$.fn.HighlightCurrentTag=function(){return this.each(function(){var $this=$(this);var currTag=$this.attr("rel");var tags=$this.find(".tagcloud").children("a");tags.each(function(){var tag=$(this);var tagTxt=tag.text();if(tagTxt===currTag){tag.addClass("current-tag");}});});}
$.fn.CommentsAPreposition=function(){if(window.location.hash){var hash=window.location.hash.substring(1),scrollToPos=$("#"+hash).offset().top,scrollElem="html";if($("#"+hash).hasClass("comment-content")){if($.browser.webkit){scrollElem="body";}
if($("#wpadminbar").length>0){scrollToPos-=$("#wpadminbar").height();}
$(scrollElem).scrollTop(scrollToPos);}}}})(jQuery);